# Generated by Django 4.2.30 on 2026-06-07 15:06

import apps.inventory.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_description', models.CharField(blank=True, max_length=100)),
                ('item_type', models.CharField(choices=[('RM', 'Raw Material'), ('SP', 'Supplies')], help_text='RM = Raw Material, SP = Supplies', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unit Measurement',
                'verbose_name_plural': 'Unit Measurements',
                'db_table': 'inv_unit_measurement',
                'ordering': ['item_type', 'unit_name'],
                'unique_together': {('unit_name', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Uppercase + underscore only. Contoh: BHP_MEDIS', max_length=100, validators=[apps.inventory.models.validate_directory_name])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('item_type', models.CharField(choices=[('RM', 'Raw Material'), ('SP', 'Supplies')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_item_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'db_table': 'inv_item_category',
                'ordering': ['item_type', 'name'],
                'unique_together': {('name', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(editable=False, max_length=100, unique=True, validators=[apps.inventory.models.validate_item_code])),
                ('item_name', models.CharField(max_length=500)),
                ('item_type', models.CharField(choices=[('RM', 'Raw Material'), ('SP', 'Supplies')], max_length=2)),
                ('is_production', models.BooleanField(default=False, verbose_name='Production')),
                ('is_purchase', models.BooleanField(default=True, verbose_name='Purchase')),
                ('price_type', models.CharField(choices=[('FIXED', 'Fixed'), ('EDITABLE', 'Editable'), ('USER_DEFINED', 'User-Defined')], default='EDITABLE', max_length=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_last_purchase_price', models.BooleanField(default=False, verbose_name='Use Last Purchase Price')),
                ('costing_method', models.CharField(choices=[('FIFO', 'First In First Out (FIFO)'), ('FEFO', 'First Expired, First Out (FEFO)'), ('LIFO', 'Last In First Out (LIFO)'), ('AVG', 'Weighted Average')], default='FIFO', max_length=10)),
                ('default_currency', models.CharField(default='IDR', max_length=10)),
                ('is_automatic_pr', models.BooleanField(default=False, verbose_name='Is Automatic PR')),
                ('view_buy', models.BooleanField(default=True)),
                ('view_sell', models.BooleanField(default=True)),
                ('view_inventory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_service', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.inventory.models.item_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.itemcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('secondary_production_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_production', to='inventory.unitmeasurement', verbose_name='Secondary Production Unit')),
                ('secondary_rr_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_rr', to='inventory.unitmeasurement', verbose_name='Secondary RR Unit')),
                ('secondary_sndo_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_sndo', to='inventory.unitmeasurement', verbose_name='Secondary SN/DO Unit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_main', to='inventory.unitmeasurement', verbose_name='Item Unit')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'inv_item',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='ItemAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('PURCHASE', 'Account for tracking purchase'), ('PURCHASE_DISCOUNT', 'Account for tracking purchase discount'), ('PURCHASE_RETURN', 'Account for tracking purchase return'), ('WIP', 'Account for tracking WIP'), ('UNBILL_REVENUE', 'Account for tracking unbill revenue'), ('SALES', 'Account for tracking sales'), ('SALES_DISCOUNT', 'Account for tracking sales discount'), ('SALES_RETURN', 'Account for tracking sales return'), ('INVENTORY', 'Account for tracking inventory')], max_length=30)),
                ('currency', models.CharField(choices=[('ALL', 'All Currency'), ('IDR', 'IDR'), ('USD', 'USD'), ('EUR', 'EUR'), ('SGD', 'SGD')], default='ALL', max_length=5)),
                ('account', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='item_links', to='accounting.account')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Item Account Link',
                'verbose_name_plural': 'Item Account Links',
                'db_table': 'inv_item_account_link',
                'unique_together': {('item', 'purpose', 'currency')},
            },
        ),
    ]
