# Generated by Django 5.0.6 on 2026-07-04 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('organization', '0004_company_smtp_from_email'),
        ('purchase', '0021_purchaseorder_close_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('receipt_type', models.CharField(choices=[('RR_PUR', 'Receipt Report For Purchase'), ('RR_SRT', 'Receipt Report For Sales Return'), ('RR_INT', 'Receipt Report For Internal'), ('RR_SRV', 'Receipt Report For Service Note'), ('RR_REP', 'Receipt Report For Repair')], default='RR_PUR', max_length=20)),
                ('receive_date', models.DateField()),
                ('vendor_sn', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_sn_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, default='')),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('awaiting', 'Awaiting'), ('approved', 'Approved'), ('rejected', 'Reject'), ('revised', 'Revised'), ('void', 'Void')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_reports', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipt_reports', to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_reports', to='purchase.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_receipt_reports', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_reports', to='purchase.vendor')),
            ],
            options={
                'db_table': 'inv_receipt_report',
                'ordering': ['-receive_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_report_items', to='inventory.item')),
                ('po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_report_items', to='purchase.purchaseorderdetail')),
                ('receipt_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.receiptreport')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitmeasurement')),
            ],
            options={
                'db_table': 'inv_receipt_report_item',
            },
        ),
    ]
