# Generated by Django 5.0.6 on 2026-07-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_receiptreport_receiptreportitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptreport',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
    ]
