# Generated by Django 5.0.6 on 2026-07-05 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_warehouse_warehousebin_receiptreportitembin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBinAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50)),
                ('document_type', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.warehousebin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_allocations', to='inventory.item')),
            ],
            options={
                'db_table': 'inv_item_bin_allocation',
            },
        ),
        migrations.DeleteModel(
            name='ReceiptReportItemBin',
        ),
    ]
