# Generated by Django 5.0.6 on 2026-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itembinallocation_delete_receiptreportitembin'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptreport',
            name='document_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_to_process', 'Ready to Process'), ('close', 'Close')], default='draft', max_length=50),
        ),
    ]
