# Generated by Django 5.0.6 on 2026-07-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_receiptreport_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptreport',
            name='transport_with',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='receiptreport',
            name='transport_with2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
