# Generated by Django 5.0.6 on 2026-07-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_receiptreport_transport_with_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptreport',
            old_name='transport_with2',
            new_name='vehicle_number',
        ),
    ]
