# Generated by Django 5.0.6 on 2026-07-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_transport_with2_receiptreport_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptreport',
            name='tracking_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptreport',
            name='tracking_status',
            field=models.TextField(blank=True, default=''),
        ),
    ]
