# Generated by Django 5.0.6 on 2026-07-11 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_receiptreport_tracking_last_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptreport',
            name='void_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_receipt_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptreport',
            name='void_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptreport',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
