# Generated by Django 4.2.30 on 2026-06-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=200)),
                ('cost_category', models.CharField(choices=[('hpp', 'HPP'), ('revenue', 'REVENUE'), ('target_hpp', 'TARGET_HPP'), ('target_opex', 'TARGET_OPEX'), ('opex', 'OPEX'), ('capex', 'CAPEX'), ('tax', 'TAX')], default='opex', max_length=20)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('template_rap', models.CharField(choices=[('none', 'NONE'), ('added', 'ADDED')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_components', to='organization.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_components', to='organization.department')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_components', to='organization.position')),
            ],
            options={
                'verbose_name': 'Budget Component',
                'verbose_name_plural': 'Budget Components',
                'db_table': 'budget_component',
                'ordering': ['order_no', 'id'],
            },
        ),
    ]
