# Generated by Django 4.2.30 on 2026-06-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('budget_component', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRAPHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_rap_header', to='budget_component.budgetcomponent')),
            ],
            options={
                'db_table': 'budget_component_template_rap',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRAPDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('header', 'Header'), ('sub_header', 'Sub Header'), ('item', 'Item')], default='header', max_length=15)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('display_number', models.CharField(blank=True, editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_rap_details', to='inventory.item')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budget_component.templaterapdetail')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='budget_component.templaterapheader')),
            ],
            options={
                'db_table': 'budget_component_template_rap_detail',
                'ordering': ['template', 'order_no', 'id'],
            },
        ),
    ]
