# Generated by Django 5.0.6 on 2026-06-27 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_journalheader_source_transaction'),
        ('budget_component', '0002_templaterapheader_templaterapdetail'),
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
        ('projects', '0004_rap_rapdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCommitmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PO', 'Purchase Order'), ('RR', 'Receipt Report'), ('CBR', 'Cashbook Request'), ('MR', 'Material Requisition')], max_length=5)),
                ('document_no', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_commitments', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_commitments', to='organization.department')),
                ('rap_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_commitments', to='projects.rapdetail')),
            ],
            options={
                'db_table': 'budget_commitment_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
