# Generated by Django 5.0.6 on 2026-07-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_component', '0003_budgetcommitmentlog'),
        ('organization', '0004_company_smtp_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcomponent',
            name='component_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('bank_obligation', 'Bank Obligation')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='budgetcomponent',
            name='custom_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='budgetcomponent',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_components', to='organization.department'),
        ),
    ]
