# Generated by Django 4.2.30 on 2026-06-14 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAPType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rap_types', to='organization.company')),
            ],
            options={
                'verbose_name': 'RAP Type',
                'verbose_name_plural': 'RAP Types',
                'db_table': 'project_rap_type',
                'ordering': ['name', 'id'],
            },
        ),
    ]
