# Generated by Django 4.2.30 on 2026-06-14 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=250)),
                ('project_type', models.CharField(default='Project Office', max_length=100)),
                ('project_category', models.CharField(default='[PC005] Project Office', max_length=150)),
                ('site_code', models.CharField(blank=True, default='', max_length=100)),
                ('site_id', models.CharField(blank=True, default='', max_length=100)),
                ('site_name', models.CharField(blank=True, default='', max_length=200)),
                ('currency_id', models.CharField(default='IDR', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_start', 'Not Start'), ('start', 'Start'), ('cancel', 'Cancel')], default='not_start', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organization.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='sales.customer')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to='organization.employee')),
            ],
            options={
                'db_table': 'project_list',
                'ordering': ['-created_at'],
            },
        ),
    ]
