# Generated by Django 4.2.30 on 2026-06-14 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_component', '0002_templaterapheader_templaterapdetail'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
        ('projects', '0003_projecttype_projectcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rap_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('rap_date', models.DateField()),
                ('month_period', models.PositiveSmallIntegerField()),
                ('year_period', models.PositiveSmallIntegerField()),
                ('cost_category', models.CharField(choices=[('hpp', 'HPP'), ('revenue', 'REVENUE'), ('target_hpp', 'TARGET_HPP'), ('target_opex', 'TARGET_OPEX'), ('opex', 'OPEX'), ('capex', 'CAPEX'), ('tax', 'TAX')], max_length=20)),
                ('activity', models.CharField(choices=[('not_set', 'Not Set'), ('investasi', 'Investasi'), ('operating', 'Operating'), ('financing', 'Financing')], default='not_set', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('document_status', models.CharField(choices=[('draft', 'Draft'), ('ready_to_process', 'Ready to Process'), ('close', 'Close')], default='draft', max_length=20)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('awaiting', 'Awaiting'), ('approved', 'Approved'), ('rejected', 'Reject'), ('revised', 'Revised')], default='draft', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raps', to='budget_component.budgetcomponent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raps', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_raps', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raps', to='organization.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raps', to='organization.position')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raps', to='projects.project')),
                ('rap_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raps', to='projects.raptype')),
            ],
            options={
                'verbose_name': 'RAP',
                'verbose_name_plural': 'RAPs',
                'db_table': 'project_rap',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAPDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('header', 'Header'), ('sub_header', 'Sub Header'), ('item', 'Item')], default='header', max_length=15)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('display_number', models.CharField(blank=True, editable=False, max_length=20)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rap_details', to='inventory.item')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.rapdetail')),
                ('rap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='projects.rap')),
            ],
            options={
                'db_table': 'project_rap_detail',
                'ordering': ['rap', 'order_no', 'id'],
            },
        ),
    ]
