# Generated by Django 5.0.6 on 2026-06-27 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('projects', '0004_rap_rapdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudgetHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actual_amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_budgets', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_header', to='projects.project')),
            ],
            options={
                'db_table': 'project_budget_header',
            },
        ),
        migrations.CreateModel(
            name='ProjectBudgetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_budget_details', to='inventory.item')),
                ('rap_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_detail', to='projects.rapdetail')),
                ('budget_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='projects.projectbudgetheader')),
            ],
            options={
                'db_table': 'project_budget_detail',
            },
        ),
    ]
