# Generated by Django 4.2.30 on 2026-06-06 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('number_prefix', models.CharField(help_text='Prefix for account numbers in this group, e.g. "1" for AKTIVA', max_length=10)),
                ('default_position', models.CharField(choices=[('DEBET', 'Debet'), ('KREDIT', 'Kredit')], default='DEBET', max_length=6)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_groups', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Group',
                'verbose_name_plural': 'Account Groups',
                'db_table': 'acc_account_group',
                'ordering': ['order', 'code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='Unique account number, e.g. 51-1.1, 51-1.1.11, 51-1.11.01', max_length=50)),
                ('account_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('HEADER', 'Header Account [Non Postable]'), ('DETAIL', 'Detail Account [Postable]'), ('DETAIL_BANK', 'Detail Bank [Postable]'), ('DETAIL_CASH', 'Detail Cash [Postable]'), ('DETAIL_CHEQUE', 'Detail Cheque Account [Postable]')], default='DETAIL', max_length=20)),
                ('language', models.CharField(choices=[('EN', 'English'), ('ID', 'Indonesian')], default='EN', max_length=10)),
                ('default_position', models.CharField(choices=[('DEBET', 'Debet'), ('KREDIT', 'Kredit')], default='DEBET', max_length=6)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('is_inter_company', models.BooleanField(default=False, help_text='Intercompany account flag')),
                ('is_cost_component', models.BooleanField(default=False, help_text='Used in cost component calculation')),
                ('is_on_duty', models.BooleanField(default=False, help_text='On-duty / operational flag')),
                ('bank_type', models.CharField(blank=True, choices=[('OPERATIONAL', 'Operational'), ('INVESTMENT', 'Investment'), ('LOAN', 'Loan'), ('PAYROLL', 'Payroll'), ('PETTY_CASH', 'Petty Cash')], help_text='Only used when account_type = DETAIL_BANK', max_length=20, null=True)),
                ('is_linked', models.BooleanField(default=False, help_text='Linked to sub-ledger (AR/AP/Asset/etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accountgroup')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'acc_account',
                'ordering': ['account_number'],
                'unique_together': {('company', 'account_number')},
            },
        ),
    ]
