# Generated by Django 4.2.30 on 2026-06-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='month_debet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='account',
            name='month_kredit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='account',
            name='month_opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='account',
            name='path',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
    ]
