# Generated by Django 4.2.30 on 2026-06-16 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
        ('projects', '0004_rap_rapdetail'),
        ('accounting', '0003_account_month_debet_account_month_kredit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralJournalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('memo', models.CharField(max_length=255)),
                ('tax_rectification', models.CharField(blank=True, max_length=50, null=True)),
                ('is_adjustment_pph', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'db_table': 'acc_general_journal_transaction',
                'ordering': ['-date', '-transaction_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('memo', models.CharField(max_length=255)),
                ('type', models.CharField(default='GEN', max_length=10)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_adjustment', models.BooleanField(default=False)),
                ('pattern_type', models.CharField(default='STANDARD', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.generaljournaltransaction')),
            ],
            options={
                'db_table': 'acc_journal_header',
            },
        ),
        migrations.CreateModel(
            name='JournalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('base_debet', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('base_kredit', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('journal_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounting.journalheader')),
            ],
            options={
                'db_table': 'acc_journal_detail',
            },
        ),
        migrations.CreateModel(
            name='GeneralJournalTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounting.generaljournaltransaction')),
            ],
            options={
                'db_table': 'acc_general_journal_transaction_detail',
            },
        ),
    ]
