# Generated by Django 4.2.30 on 2026-06-16 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        ('accounting', '0004_generaljournaltransaction_journalheader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaljournaltransaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor'),
        ),
    ]
