# Generated by Django 4.2.30 on 2026-06-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_generaljournaltransaction_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalheader',
            name='source_transaction',
        ),
    ]
