# Generated by Django 5.0.6 on 2026-07-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_remove_globallinkedaccount_accrued_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_tax_in',
            field=models.BooleanField(default=False, help_text='Indicates if this account is the Input Tax (PPN Masukan) account.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_on_duty',
            field=models.BooleanField(default=False, help_text='Indicates if this account is used for duty/tax logic in other modules.'),
        ),
    ]
