# Generated by Django 5.0.6 on 2026-07-11 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_account_is_tax_in_alter_account_is_on_duty'),
        ('inventory', '0010_receiptreport_void_by_receiptreport_void_date_and_more'),
        ('master_type', '0003_paymentto'),
        ('organization', '0004_company_smtp_from_email'),
        ('projects', '0005_projectbudgetheader_projectbudgetdetail'),
        ('purchase', '0026_alter_purchaseinvoice_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbookReqHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('duration_due_date', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('notes_payment_to', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vendor_invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('unpaid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('is_sumbangan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_type.paymentto')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchaseinvoice')),
                ('requestor_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.department')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_type.transactiontype')),
            ],
            options={
                'verbose_name': 'Cashbook Request Header',
                'db_table': 'acc_cashbook_req_header',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashbookReqDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounting.cashbookreqheader')),
            ],
            options={
                'verbose_name': 'Cashbook Request Detail',
                'db_table': 'acc_cashbook_req_detail',
            },
        ),
    ]
