# Generated by Django 5.0.6 on 2026-07-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_cashbookreqheader_cashbookreqdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookreqheader',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting', 'Awaiting'), ('approved', 'Approved'), ('rejected', 'Reject'), ('revised', 'Revised')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='cashbookreqheader',
            name='document_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_to_process', 'Ready to Process'), ('close', 'Close')], default='draft', max_length=20),
        ),
    ]
