# Generated by Django 5.0.6 on 2026-07-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_cashbookreqheader_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookreqheader',
            name='paid_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('half_paid', 'Half Paid'), ('full_paid', 'Full Paid')], default='not_paid', max_length=20),
        ),
    ]
