# Generated by Django 5.0.6 on 2026-07-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_cashbookreqheader_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookreqheader',
            name='allow_previous_year_budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashbookreqheader',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
