# Generated by Django 5.0.6 on 2026-07-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_cashbookreqheader_allow_previous_year_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookreqheader',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
