# Generated by Django 5.0.6 on 2026-07-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_cashbookreqheader_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookreqheader',
            name='usage_for',
            field=models.CharField(choices=[('Purchase Invoice Payment', 'Purchase Invoice Payment'), ('Project Cash Advanced', 'Project Cash Advanced'), ('Purchase Order Down Payment', 'Purchase Order Down Payment'), ('Bank Obligation Principal', 'Bank Obligation Principal'), ('Bank Obligation Interest', 'Bank Obligation Interest')], default='Purchase Invoice Payment', max_length=50),
        ),
    ]
