# Generated by Django 5.0.6 on 2026-07-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_cashbookreqheader_usage_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookreqheader',
            name='paid_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cashbookreqheader',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
