# Generated by Django 5.0.6 on 2026-07-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_cashbookreqheader_paid_tax_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashbookreqheader',
            old_name='paid_tax_amount',
            new_name='unpaid_tax_amount',
        ),
    ]
