# Generated by Django 5.0.6 on 2026-07-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_rename_paid_tax_amount_cashbookreqheader_unpaid_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookreqheader',
            name='reason_allow_previous_year_budget',
            field=models.TextField(blank=True, null=True),
        ),
    ]
