# Generated by Django 5.0.6 on 2026-07-14 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_cashbookreqheader_reason_allow_previous_year_budget'),
        ('projects', '0005_projectbudgetheader_projectbudgetdetail'),
        ('purchase', '0026_alter_purchaseinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookreqdetail',
            name='is_tax_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashbookreqdetail',
            name='no_faktur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cashbookreqdetail',
            name='npwp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cashbookreqdetail',
            name='rap_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_details', to='projects.rapdetail'),
        ),
        migrations.AddField(
            model_name='cashbookreqdetail',
            name='tax_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='cashbookreqdetail',
            name='tax_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashbookreqdetail',
            name='tax_in_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cashbookreqheader',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbook_requests', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='cashbookreqheader',
            name='is_pr_for_lpj',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashbookreqheader',
            name='is_reimbursement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashbookreqheader',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashbookreqheader',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_requests', to='purchase.vendor'),
        ),
    ]
