# Generated by Django 5.0.6 on 2026-07-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_cashbookreqdetail_is_tax_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbookreqdetail',
            name='tax_in_amount',
        ),
    ]
