# Generated by Django 5.0.6 on 2026-07-18 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_remove_cashbookreqdetail_tax_in_amount'),
        ('master_type', '0003_paymentto'),
        ('organization', '0004_company_smtp_from_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField()),
                ('plafond', models.DecimalField(decimal_places=2, max_digits=18)),
                ('jangka_waktu', models.IntegerField(help_text='In months')),
                ('bunga_margin', models.DecimalField(decimal_places=2, help_text='Percentage per year', max_digits=5)),
                ('loan_type', models.CharField(choices=[('NON_SINDIKASI', 'Non Sindikasi'), ('SINDIKASI', 'Sindikasi'), ('TRANCHE_1', 'Tranche 1'), ('TRANCHE_2', 'Tranche 2'), ('TRANCHE_3', 'Tranche 3'), ('KREDIT_INVESTASI', 'Kredit Investasi'), ('KREDIT_MODAL_KERJA', 'Kredit Modal Kerja'), ('KREDIT_REKENING_KORAN', 'Kredit Rekening Koran'), ('BACK_TO_BACK', 'Back To Back'), ('CAPITAL_LEASE', 'Capital Lease'), ('OPERATING_LEASE', 'Operating Lease')], default='NON_SINDIKASI', max_length=50)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_bunga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('account_pokok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_type.masterbank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_obligations', to='organization.company')),
            ],
            options={
                'db_table': 'acc_bank_obligation',
            },
        ),
        migrations.CreateModel(
            name='BankObligationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('bulan', models.DateField()),
                ('tanggal_pencairan', models.DateField()),
                ('sisa_pokok', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pokok', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diskon_margin', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_angsuran', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_cbr_pokok', models.BooleanField(default=False)),
                ('is_cbr_bunga', models.BooleanField(default=False)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounting.bankobligation')),
            ],
            options={
                'db_table': 'acc_bank_obligation_detail',
                'ordering': ['no'],
            },
        ),
    ]
