# Generated by Django 5.0.6 on 2026-07-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_bankobligation_bankobligationdetail'),
        ('budget_component', '0003_budgetcommitmentlog'),
        ('organization', '0004_company_smtp_from_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankObligationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bunga_budget_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bunga_settings', to='budget_component.budgetcomponent')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_obligation_setting', to='organization.company')),
                ('pokok_budget_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokok_settings', to='budget_component.budgetcomponent')),
            ],
            options={
                'db_table': 'bank_obligation_setting',
            },
        ),
    ]
