# Generated by Django 5.0.6 on 2026-07-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_bankobligationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookreqdetail',
            name='bank_obligation_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_details', to='accounting.bankobligationdetail'),
        ),
        migrations.AddField(
            model_name='cashbookreqheader',
            name='bank_obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_requests', to='accounting.bankobligation'),
        ),
    ]
