# Generated by Django 5.0.6 on 2026-07-20 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_cashbookreqdetail_bank_obligation_detail_and_more'),
        ('projects', '0005_projectbudgetheader_projectbudgetdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookreqheader',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
        ),
    ]
