# Generated by Django 5.0.6 on 2026-07-25 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_cashbookreqheader_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookreqheader',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashbookreqheader',
            name='close_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wht', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('wht_type', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('budgetrequest_status', models.CharField(choices=[('None', 'None'), ('ReadyToProcess', 'Ready to Process'), ('ReadyToPay', 'Ready to Pay'), ('ApproveForPayment', 'Approve for Payment')], default='None', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashbook_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_request', to='accounting.cashbookreqheader')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Request',
                'db_table': 'acc_budget_request',
            },
        ),
    ]
