# Generated by Django 5.0.6 on 2026-07-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_budgetrequest_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrequest',
            name='payment_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
