# Generated by Django 5.0.6 on 2026-07-11 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_company_smtp_from_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_name_en', models.CharField(max_length=150)),
                ('type_name_id', models.CharField(max_length=150)),
                ('table_name', models.CharField(default='TrsType', max_length=50)),
                ('order_no', models.IntegerField(default=0)),
                ('is_not_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_types', to='organization.company')),
            ],
            options={
                'verbose_name': 'Transaction Type',
                'verbose_name_plural': 'Transaction Types',
                'db_table': 'master_transaction_type',
                'ordering': ['order_no', 'type_code'],
            },
        ),
    ]
