# Generated by Django 5.0.6 on 2026-07-11 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_type', '0001_initial'),
        ('organization', '0004_company_smtp_from_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_name_id', models.CharField(max_length=150)),
                ('is_not_active', models.BooleanField(default=False)),
                ('order_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_banks', to='organization.company')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'db_table': 'master_bank',
                'ordering': ['order_no', 'bank_code'],
            },
        ),
    ]
