# Generated by Django 5.0.6 on 2026-07-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_type', '0002_masterbank'),
        ('organization', '0004_company_smtp_from_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bank_branch', models.CharField(max_length=255)),
                ('bank_city', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('is_hide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payment_tos', to='master_type.masterbank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_tos', to='organization.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_tos', to='organization.department')),
            ],
            options={
                'verbose_name': 'Payment To',
                'verbose_name_plural': 'Payment To',
                'db_table': 'master_payment_to',
                'ordering': ['-id'],
            },
        ),
    ]
