# Generated by Django 4.2.30 on 2026-06-13 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_component', '0002_templaterapheader_templaterapdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualBudgetHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked = tidak bisa diedit lagi.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_budgets', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_budgets_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_budgets', to='organization.department')),
            ],
            options={
                'verbose_name': 'Annual Budget Header',
                'verbose_name_plural': 'Annual Budget Headers',
                'db_table': 'annual_budget_header',
                'ordering': ['-year', 'department__name'],
                'unique_together': {('company', 'department', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AnnualBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveSmallIntegerField(default=0)),
                ('jan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('feb', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('mar', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('apr', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('jun', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('jul', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('aug', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sep', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('oct', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nov', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dec', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('jan_reloc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('feb_reloc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('mar_reloc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('apr_reloc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('may_reloc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('jun_reloc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('jul_reloc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('aug_reloc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sep_reloc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('oct_reloc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nov_reloc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dec_reloc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_budget_lines', to='budget_component.budgetcomponent')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='annual_budget.annualbudgetheader')),
            ],
            options={
                'verbose_name': 'Annual Budget Line',
                'verbose_name_plural': 'Annual Budget Lines',
                'db_table': 'annual_budget_line',
                'ordering': ['order_no', 'id'],
                'unique_together': {('header', 'budget_component')},
            },
        ),
        migrations.CreateModel(
            name='AnnualBudgetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('old_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('new_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_budget_logs', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='annual_budget.annualbudgetline')),
            ],
            options={
                'db_table': 'annual_budget_log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
