# Generated by Django 4.2.30 on 2026-06-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annualbudgetline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='annualbudgetline',
            name='cost_category',
            field=models.CharField(choices=[('hpp', 'HPP'), ('revenue', 'REVENUE'), ('target_hpp', 'TARGET_HPP'), ('target_opex', 'TARGET_OPEX'), ('opex', 'OPEX'), ('capex', 'CAPEX'), ('tax', 'TAX')], default='opex', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='annualbudgetline',
            unique_together={('header', 'cost_category')},
        ),
        migrations.RemoveField(
            model_name='annualbudgetline',
            name='budget_component',
        ),
    ]
