# Generated by Django 5.0.6 on 2026-07-20 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_budget', '0002_alter_annualbudgetline_unique_together_and_more'),
        ('budget_component', '0004_budgetcomponent_component_type_and_more'),
        ('organization', '0004_company_smtp_from_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annualbudgetheader',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='annualbudgetline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='annualbudgetheader',
            name='budget_type',
            field=models.CharField(choices=[('STANDARD', 'Standard (Department)'), ('BANK_OBLIGATION', 'Bank Obligation')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='annualbudgetline',
            name='budget_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_budget_lines', to='budget_component.budgetcomponent'),
        ),
        migrations.AlterField(
            model_name='annualbudgetheader',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_budgets', to='organization.department'),
        ),
        migrations.AddConstraint(
            model_name='annualbudgetheader',
            constraint=models.UniqueConstraint(condition=models.Q(('budget_type', 'STANDARD')), fields=('company', 'department', 'year'), name='unique_standard_annual_budget'),
        ),
        migrations.AddConstraint(
            model_name='annualbudgetheader',
            constraint=models.UniqueConstraint(condition=models.Q(('budget_type', 'BANK_OBLIGATION')), fields=('company', 'year'), name='unique_bank_obligation_annual_budget'),
        ),
    ]
