# Generated by Django 4.2.30 on 2026-06-14 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(choices=[('RAP', 'Rencana Anggaran Pelaksana (RAP)')], help_text='Kode transaksi/dokumen, e.g. RAP, PR, PO', max_length=20)),
                ('document_id', models.CharField(help_text='ID of the target document instance', max_length=50)),
                ('document_number', models.CharField(help_text='Nomor dokumen/kode transaksi, e.g. RAP-2026-0001', max_length=100)),
                ('basis', models.CharField(choices=[('AMOUNT', 'Total Amount (After Disc & Tax)'), ('QUANTITY', 'Total Quantity')], default='AMOUNT', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('current_step_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='organization.company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('creator_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator_approval_requests', to='organization.position')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'db_table': 'approval_request',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'document_code', 'document_id')},
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(choices=[('RAP', 'Rencana Anggaran Pelaksana (RAP)')], max_length=20)),
                ('document_id', models.CharField(max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('role', models.CharField(choices=[('PREPARED_BY', 'Prepared By'), ('APPROVED_BY', 'Approved By'), ('ACKNOWLEDGE_BY', 'Acknowledge By'), ('ACCOUNTING_DEPT', 'Accounting Dept'), ('CHECKED_BY', 'Checked By'), ('VERIFIED_BY', 'Verified By'), ('ACCEPTED_BY', 'Accepted By')], max_length=20)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_draw', models.TextField(blank=True, help_text='Base64 canvas drawing snapshot at time of signing')),
                ('signature_image', models.CharField(blank=True, help_text='URL path to uploaded signature image snapshot at time of signing', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_signatures', to='organization.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_signatures', to='organization.position')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Signature',
                'verbose_name_plural': 'Document Signatures',
                'db_table': 'document_signature',
                'ordering': ['document_code', 'document_id', 'step_number'],
                'unique_together': {('company', 'document_code', 'document_id', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('role', models.CharField(choices=[('PREPARED_BY', 'Prepared By'), ('APPROVED_BY', 'Approved By'), ('ACKNOWLEDGE_BY', 'Acknowledge By'), ('ACCOUNTING_DEPT', 'Accounting Dept'), ('CHECKED_BY', 'Checked By'), ('VERIFIED_BY', 'Verified By'), ('ACCEPTED_BY', 'Accepted By')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approval.approvalrequest')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_steps', to='organization.position')),
            ],
            options={
                'verbose_name': 'Approval Request Step',
                'verbose_name_plural': 'Approval Request Steps',
                'db_table': 'approval_request_step',
                'ordering': ['step_number'],
                'unique_together': {('approval_request', 'step_number')},
            },
        ),
    ]
