# Generated by Django 4.2.30 on 2026-06-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_approvalrequest_documentsignature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrix',
            name='document_code',
            field=models.CharField(choices=[('RAP', 'Rencana Anggaran Pelaksana (RAP)'), ('GEJ', 'General Journal (GEJ)')], help_text='Kode transaksi/dokumen, e.g. RAP, PR, PO', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='document_code',
            field=models.CharField(choices=[('RAP', 'Rencana Anggaran Pelaksana (RAP)'), ('GEJ', 'General Journal (GEJ)')], help_text='Kode transaksi/dokumen, e.g. RAP, PR, PO', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='document_code',
            field=models.CharField(choices=[('RAP', 'Rencana Anggaran Pelaksana (RAP)'), ('GEJ', 'General Journal (GEJ)')], max_length=20),
        ),
    ]
