# Generated by Django 5.0.6 on 2026-07-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_alter_approvalmatrix_document_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrix',
            name='document_code',
            field=models.CharField(choices=[('RAP', 'Rencana Anggaran Pelaksana (RAP)'), ('GEJ', 'General Journal (GEJ)'), ('PR', 'Purchase Requisition (PR)'), ('PO', 'Purchase Order (PO)'), ('CC', 'Completion Certificate (CC)'), ('GRN', 'Good Receipt Note (GRN)')], help_text='Kode transaksi/dokumen, e.g. RAP, PR, PO', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='document_code',
            field=models.CharField(choices=[('RAP', 'Rencana Anggaran Pelaksana (RAP)'), ('GEJ', 'General Journal (GEJ)'), ('PR', 'Purchase Requisition (PR)'), ('PO', 'Purchase Order (PO)'), ('CC', 'Completion Certificate (CC)'), ('GRN', 'Good Receipt Note (GRN)')], help_text='Kode transaksi/dokumen, e.g. RAP, PR, PO', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='document_code',
            field=models.CharField(choices=[('RAP', 'Rencana Anggaran Pelaksana (RAP)'), ('GEJ', 'General Journal (GEJ)'), ('PR', 'Purchase Requisition (PR)'), ('PO', 'Purchase Order (PO)'), ('CC', 'Completion Certificate (CC)'), ('GRN', 'Good Receipt Note (GRN)')], max_length=20),
        ),
    ]
