# Generated by Django 5.0.6 on 2026-07-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_alter_approvalmatrix_document_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrix',
            name='document_code',
            field=models.CharField(choices=[('RAP', 'Rencana Anggaran Pelaksana (RAP)'), ('GEJ', 'General Journal (GEJ)'), ('PR', 'Purchase Requisition (PR)'), ('PO', 'Purchase Order (PO)'), ('CC', 'Completion Certificate (CC)'), ('GRN', 'Good Receipt Note (GRN)'), ('RECEIPT_REPORT', 'Receipt Report (RR)'), ('CBR_PI', 'Payment Request (Purchase Invoice)')], help_text='Kode transaksi/dokumen, e.g. RAP, PR, PO', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='document_code',
            field=models.CharField(choices=[('RAP', 'Rencana Anggaran Pelaksana (RAP)'), ('GEJ', 'General Journal (GEJ)'), ('PR', 'Purchase Requisition (PR)'), ('PO', 'Purchase Order (PO)'), ('CC', 'Completion Certificate (CC)'), ('GRN', 'Good Receipt Note (GRN)'), ('RECEIPT_REPORT', 'Receipt Report (RR)'), ('CBR_PI', 'Payment Request (Purchase Invoice)')], help_text='Kode transaksi/dokumen, e.g. RAP, PR, PO', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='document_code',
            field=models.CharField(choices=[('RAP', 'Rencana Anggaran Pelaksana (RAP)'), ('GEJ', 'General Journal (GEJ)'), ('PR', 'Purchase Requisition (PR)'), ('PO', 'Purchase Order (PO)'), ('CC', 'Completion Certificate (CC)'), ('GRN', 'Good Receipt Note (GRN)'), ('RECEIPT_REPORT', 'Receipt Report (RR)'), ('CBR_PI', 'Payment Request (Purchase Invoice)')], max_length=20),
        ),
    ]
