# Generated by Django 6.0.5 on 2026-05-29 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'rbac_module',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=True, help_text='Active / Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authorization Group',
                'verbose_name_plural': 'Authorization Groups',
                'db_table': 'rbac_authorization_group',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('url_path', models.CharField(blank=True, help_text='Frontend route, e.g. /gl/journal-entry', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='rbac.module')),
            ],
            options={
                'verbose_name': 'Function',
                'verbose_name_plural': 'Functions',
                'db_table': 'rbac_function',
                'ordering': ['module__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_print', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorization_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_functions', to='rbac.authorizationgroup')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_functions', to='rbac.function')),
            ],
            options={
                'verbose_name': 'Group Function',
                'verbose_name_plural': 'Group Functions',
                'db_table': 'rbac_group_function',
                'unique_together': {('authorization_group', 'function')},
            },
        ),
        migrations.CreateModel(
            name='UserAuthorizationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_groups', to=settings.AUTH_USER_MODEL)),
                ('authorization_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_auth_groups', to='rbac.authorizationgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_auth_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Authorization Group',
                'verbose_name_plural': 'User Authorization Groups',
                'db_table': 'rbac_user_authorization_group',
                'unique_together': {('user', 'authorization_group')},
            },
        ),
    ]
