# Generated by Django 4.2.30 on 2026-05-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['module__order', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='function',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.function'),
        ),
    ]
