# Generated by Django 4.2.30 on 2026-06-13 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='OPEN', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_periods', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounting_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting Period',
                'verbose_name_plural': 'Accounting Periods',
                'db_table': 'acc_accounting_period',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='AnnualPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='OPEN', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_periods', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annual_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annual Period',
                'verbose_name_plural': 'Annual Periods',
                'db_table': 'acc_annual_period',
                'ordering': ['-year'],
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='OPEN', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='accounting_period.annualperiod')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_periods', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monthly_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Period',
                'verbose_name_plural': 'Monthly Periods',
                'db_table': 'acc_monthly_period',
                'ordering': ['-year', 'month'],
            },
        ),
        migrations.CreateModel(
            name='QuarterPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='OPEN', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='accounting_period.annualperiod')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_periods', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quarter_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quarter Period',
                'verbose_name_plural': 'Quarter Periods',
                'db_table': 'acc_quarter_period',
                'ordering': ['-year', 'quarter'],
                'unique_together': {('company', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='PeriodActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('ANNUAL', 'Annual Period'), ('QUARTER', 'Quarter Period'), ('MONTHLY', 'Monthly Period'), ('ACCOUNTING', 'Accounting Period')], max_length=20)),
                ('action', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], help_text='The new status after this action (OPEN or CLOSE)', max_length=5)),
                ('reason', models.TextField(help_text='Reason given by the user for this action')),
                ('period_label', models.CharField(help_text='Human-readable snapshot of the period at log time, e.g. "June 2026"', max_length=100)),
                ('period_status_after', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], help_text='Status of the period after the action', max_length=5)),
                ('actioned_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounting_period.accountingperiod')),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('annual_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounting_period.annualperiod')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_activity_logs', to='organization.company')),
                ('monthly_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounting_period.monthlyperiod')),
                ('quarter_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounting_period.quarterperiod')),
            ],
            options={
                'verbose_name': 'Period Activity Log',
                'verbose_name_plural': 'Period Activity Logs',
                'db_table': 'acc_period_activity_log',
                'ordering': ['-actioned_at'],
            },
        ),
        migrations.AddField(
            model_name='monthlyperiod',
            name='quarter_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='accounting_period.quarterperiod'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='monthly_period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_period', to='accounting_period.monthlyperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyperiod',
            unique_together={('company', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('company', 'year', 'month')},
        ),
    ]
