# Generated by Django 4.2.30 on 2026-06-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('variety', models.CharField(blank=True, default='', max_length=100)),
                ('tax_number', models.CharField(blank=True, default='', max_length=50)),
                ('nppkp', models.CharField(blank=True, default='', max_length=50)),
                ('is_leasing', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('alternative_email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField(blank=True, default='')),
                ('country', models.CharField(default='Indonesia', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('area_code', models.CharField(choices=[('other', '[Other] Other'), ('jakarta', 'Jakarta'), ('bandung', 'Bandung'), ('surabaya', 'Surabaya')], default='other', max_length=20)),
                ('phone_1', models.CharField(max_length=30)),
                ('phone_2', models.CharField(blank=True, default='', max_length=30)),
                ('fax', models.CharField(blank=True, default='', max_length=30)),
                ('currency', models.CharField(choices=[('IDR', 'IDR'), ('USD', 'USD'), ('EUR', 'EUR'), ('SGD', 'SGD')], default='IDR', max_length=5)),
                ('tolerance_difference', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=100)),
                ('bank_city', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=200)),
                ('term_and_condition', models.TextField(blank=True, default='')),
                ('company_financial_capability', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notary_name', models.CharField(blank=True, default='', max_length=200)),
                ('letter_no_date', models.CharField(blank=True, default='', max_length=200)),
                ('notary_name_2', models.CharField(blank=True, default='', max_length=200)),
                ('letter_no_date_2', models.CharField(blank=True, default='', max_length=200)),
                ('letter_of_endorsement', models.CharField(blank=True, default='', max_length=200)),
                ('no_siup', models.CharField(blank=True, default='', max_length=100)),
                ('expired_date_siup', models.DateField(blank=True, null=True)),
                ('no_tdp', models.CharField(blank=True, default='', max_length=100)),
                ('expired_date_tdp', models.DateField(blank=True, null=True)),
                ('no_sk_domisili', models.CharField(blank=True, default='', max_length=100)),
                ('expired_date_sk_domisili', models.DateField(blank=True, null=True)),
                ('no_siujk', models.CharField(blank=True, default='', max_length=100)),
                ('expired_date_siujk', models.DateField(blank=True, null=True)),
                ('kriteria_usaha', models.CharField(blank=True, choices=[('usaha_kecil', 'Usaha Kecil'), ('usaha_menengah', 'Usaha Menengah'), ('usaha_besar', 'Usaha Besar')], default='usaha_kecil', max_length=20)),
                ('item_type_asset', models.BooleanField(default=True)),
                ('item_type_fg', models.BooleanField(default=True)),
                ('item_type_rm', models.BooleanField(default=True)),
                ('item_type_supplies', models.BooleanField(default=True)),
                ('item_type_wip', models.BooleanField(default=True)),
                ('item_type_maintenance', models.BooleanField(default=True)),
                ('item_type_subcont', models.BooleanField(default=True)),
                ('is_sister_company', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('hold', 'Hold')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchases_vendor',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Vendor Categories',
                'db_table': 'purchases_vendor_category',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VendorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'purchases_vendor_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due', models.CharField(choices=[('tanpa_cicilan', 'Tanpa Cicilan'), ('net_30', 'Net 30'), ('net_60', 'Net 60'), ('cod', 'COD')], default='tanpa_cicilan', max_length=20)),
                ('balance_due_days', models.PositiveIntegerField(default=0)),
                ('tax_code', models.CharField(choices=[('pph_23_45', 'PPh 23 Rate 4.5 %'), ('pph_23_2', 'PPh 23 Rate 2 %'), ('pph_23_15', 'PPh 23 Rate 1.5 %'), ('non', 'Non PPh')], default='non', max_length=20)),
                ('use_vendor_tax_code', models.BooleanField(default=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='purchase.vendor')),
            ],
            options={
                'db_table': 'purchases_vendor_terms',
            },
        ),
        migrations.CreateModel(
            name='VendorContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('dr', 'Dr'), ('prof', 'Prof')], default='', max_length=10)),
                ('job_title', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10)),
                ('spouse', models.CharField(blank=True, default='', max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('country', models.CharField(default='Indonesia', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.CharField(choices=[('other', 'O - Other'), ('jakarta', 'Jakarta'), ('bandung', 'Bandung'), ('surabaya', 'Surabaya')], default='other', max_length=20)),
                ('home_address', models.TextField(blank=True, default='')),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=30)),
                ('fax', models.CharField(blank=True, default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='purchase.vendor')),
            ],
            options={
                'db_table': 'purchases_vendor_contact_person',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.vendorcategory'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='organization.company'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendorgroup'),
        ),
        migrations.CreateModel(
            name='VendorLinkedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('ap', 'Account Payable (A/P)'), ('deposit', 'Vendor Deposit'), ('down_payment', 'Vendor Down Payment')], max_length=30)),
                ('currency_scope', models.CharField(choices=[('all', 'All'), ('IDR', 'IDR'), ('USD', 'USD'), ('EUR', 'EUR'), ('SGD', 'SGD')], default='all', max_length=5)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='purchase.vendor')),
            ],
            options={
                'db_table': 'purchases_vendor_linked_account',
                'unique_together': {('vendor', 'account_type', 'currency_scope')},
            },
        ),
    ]
