# Generated by Django 4.2.30 on 2026-06-18 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_component', '0002_templaterapheader_templaterapdetail'),
        ('projects', '0004_rap_rapdetail'),
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('pr_date', models.DateField()),
                ('pr_type', models.CharField(choices=[('RM', 'Raw Material'), ('SP', 'Supplies'), ('AST', 'Asset')], default='RM', max_length=5)),
                ('cost_category', models.CharField(blank=True, default='', max_length=50)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('etd', models.DateField(blank=True, null=True, verbose_name='Estimated Time Delivery')),
                ('delivery_point', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('document_status', models.CharField(choices=[('draft', 'Draft'), ('ready_to_process', 'Ready to Process'), ('close', 'Close')], default='draft', max_length=20)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('awaiting', 'Awaiting'), ('approved', 'Approved'), ('rejected', 'Reject'), ('revised', 'Revised')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='budget_component.budgetcomponent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requisitions', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='organization.department')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='projects.project')),
                ('rap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='projects.rap')),
            ],
            options={
                'verbose_name': 'Purchase Requisition',
                'verbose_name_plural': 'Purchase Requisitions',
                'db_table': 'purchases_pr_header',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('final_unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pr_details', to='inventory.item')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='purchase.purchaserequisition')),
                ('rap_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_details', to='projects.rapdetail')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_details', to='inventory.unitmeasurement')),
            ],
            options={
                'db_table': 'purchases_pr_detail',
                'ordering': ['pr', 'order_no', 'id'],
            },
        ),
    ]
