# Generated by Django 4.2.30 on 2026-06-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchaserequisition_purchaserequisitiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='pr_class',
            field=models.CharField(default='Common', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='repetition',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='request_type',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
