# Generated by Django 4.2.30 on 2026-06-20 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_component', '0002_templaterapheader_templaterapdetail'),
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
        ('inventory', '0001_initial'),
        ('projects', '0004_rap_rapdetail'),
        ('purchase', '0003_purchaserequisition_pr_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('po_date', models.DateField()),
                ('po_type', models.CharField(choices=[('normal', 'Normal'), ('vat_include', 'VAT Include')], default='normal', max_length=20)),
                ('po_currency', models.CharField(default='IDR', max_length=10)),
                ('tax_currency', models.CharField(default='IDR', max_length=10)),
                ('freight_currency', models.CharField(default='IDR', max_length=10)),
                ('is_sister_company', models.BooleanField(default=False)),
                ('vendor_so_number', models.CharField(blank=True, default='', max_length=100)),
                ('is_import', models.BooleanField(default=False)),
                ('print_out_type', models.CharField(choices=[('po', 'Purchase Order'), ('spk', 'Surat Perintah Kerja')], default='po', max_length=10)),
                ('term_and_condition', models.TextField(blank=True, default='')),
                ('mandatory_update_material', models.BooleanField(default=False)),
                ('not_regular', models.BooleanField(default=False)),
                ('ppn', models.BooleanField(default=False, verbose_name='PPN')),
                ('is_subcontract', models.BooleanField(default=False)),
                ('subcontract_notes', models.TextField(blank=True, default='')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='Estimated Time Delivery')),
                ('notes', models.TextField(blank=True, default='')),
                ('document_status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('close', 'Close'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('awaiting', 'Awaiting'), ('approved', 'Approved'), ('rejected', 'Reject'), ('revised', 'Revised')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('payment_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='projects.project')),
                ('rap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='projects.rap')),
                ('requestor_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='organization.department')),
                ('rr_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rr_purchase_orders', to='purchase.vendor')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchase.vendor')),
                ('vi_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vi_purchase_orders', to='purchase.vendor')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'purchases_po_header',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='vendorterms',
            name='tax_code',
            field=models.CharField(choices=[('none', 'None'), ('pph_23_rate_15', 'PPH 23 RATE 15 %'), ('pph_23_rate_2', 'PPH 23 RATE 2 %'), ('pph_23_rate_4', 'PPH 23 RATE 4%'), ('pph_23_rate_4_5', 'PPh 23 RATE 4.5 %'), ('pph_23_rate_7_5', 'PPH 23 RATE 7.5 %'), ('pph_4_2_rate_10', 'PPH 4(2) RATE 10%'), ('pph_4_2_rate_2', 'PPH 4(2) RATE 2%'), ('pph_4_2_rate_3', 'PPH 4(2) RATE 3%'), ('pph_4_2_rate_4', 'PPH 4(2) RATE 4%'), ('ppn_01', 'PPN 01 %'), ('ppn_10', 'PPN 10 %'), ('ppn_10_euro', 'PPN 10% (EURO)'), ('ppn_11', 'PPN 11 %'), ('ppn_15', 'PPN 15%'), ('non', 'Non PPh')], default='non', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseOrderPaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_desc', models.CharField(max_length=200)),
                ('duration_due', models.CharField(blank=True, default='', max_length=50)),
                ('duration_due_percent', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('doc_reff', models.CharField(blank=True, default='', max_length=100)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='purchase.purchaseorder')),
            ],
            options={
                'db_table': 'purchases_po_payment_term',
                'ordering': ['po', 'order_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('tax1', models.CharField(choices=[('none', 'None'), ('pph_23_rate_15', 'PPH 23 RATE 15 %'), ('pph_23_rate_2', 'PPH 23 RATE 2 %'), ('pph_23_rate_4', 'PPH 23 RATE 4%'), ('pph_23_rate_4_5', 'PPh 23 RATE 4.5 %'), ('pph_23_rate_7_5', 'PPH 23 RATE 7.5 %'), ('pph_4_2_rate_10', 'PPH 4(2) RATE 10%'), ('pph_4_2_rate_2', 'PPH 4(2) RATE 2%'), ('pph_4_2_rate_3', 'PPH 4(2) RATE 3%'), ('pph_4_2_rate_4', 'PPH 4(2) RATE 4%'), ('ppn_01', 'PPN 01 %'), ('ppn_10', 'PPN 10 %'), ('ppn_10_euro', 'PPN 10% (EURO)'), ('ppn_11', 'PPN 11 %'), ('ppn_15', 'PPN 15%'), ('non', 'Non PPh')], default='none', max_length=30)),
                ('tax2', models.CharField(choices=[('none', 'None'), ('pph_23_rate_15', 'PPH 23 RATE 15 %'), ('pph_23_rate_2', 'PPH 23 RATE 2 %'), ('pph_23_rate_4', 'PPH 23 RATE 4%'), ('pph_23_rate_4_5', 'PPh 23 RATE 4.5 %'), ('pph_23_rate_7_5', 'PPH 23 RATE 7.5 %'), ('pph_4_2_rate_10', 'PPH 4(2) RATE 10%'), ('pph_4_2_rate_2', 'PPH 4(2) RATE 2%'), ('pph_4_2_rate_3', 'PPH 4(2) RATE 3%'), ('pph_4_2_rate_4', 'PPH 4(2) RATE 4%'), ('ppn_01', 'PPN 01 %'), ('ppn_10', 'PPN 10 %'), ('ppn_10_euro', 'PPN 10% (EURO)'), ('ppn_11', 'PPN 11 %'), ('ppn_15', 'PPN 15%'), ('non', 'Non PPh')], default='none', max_length=30)),
                ('estimated_date', models.DateField(blank=True, null=True)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('budget_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_component.budgetcomponent')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_details', to='inventory.item')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='purchase.purchaseorder')),
                ('pr_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_details', to='purchase.purchaserequisitiondetail')),
                ('rap_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_details', to='projects.rapdetail')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_details', to='inventory.unitmeasurement')),
            ],
            options={
                'db_table': 'purchases_po_detail',
                'ordering': ['po', 'order_no', 'id'],
            },
        ),
    ]
