# Generated by Django 4.2.30 on 2026-06-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchaseorder_alter_vendorterms_tax_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='partial_cancellation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
