# Generated by Django 4.2.30 on 2026-06-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchaseorder_partial_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_type',
            field=models.CharField(choices=[('RM', 'Raw Material'), ('SP', 'Supplies'), ('AST', 'Asset')], default='RM', max_length=20),
        ),
    ]
