# Generated by Django 4.2.30 on 2026-06-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_purchaseorder_paid_amount_purchaseorder_po_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='allow_previous_year_budget',
            field=models.BooleanField(default=False, verbose_name='Allow Previous Year Budget RAP'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
