# Generated by Django 5.0.6 on 2026-06-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_purchaseorder_allow_previous_year_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pr_class',
            field=models.CharField(default='Common', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='repetition',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
