# Generated by Django 5.0.6 on 2026-06-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_purchaseorder_pr_class_purchaseorder_repetition'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_point',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
