# Generated by Django 5.0.6 on 2026-06-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_purchaseorder_delivery_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
