# Generated by Django 5.0.6 on 2026-06-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_purchaseorderdetail_deduction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='paid_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
