# Generated by Django 5.0.6 on 2026-06-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_purchaseorderdetail_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrnSesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('GRN', 'GRN'), ('SES', 'SES')], default='GRN', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'purchases_grn_ses_document',
                'ordering': ['document_name'],
            },
        ),
    ]
