# Generated by Django 5.0.6 on 2026-06-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_grnsesdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', models.CharField(max_length=100, unique=True)),
                ('document_date', models.DateField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('GRN', 'GRN'), ('BAST', 'BAST')], default='GRN', max_length=10)),
                ('document_date_from_vendor', models.DateField()),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('approval_status', models.CharField(default='PENDING', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorderpaymentterm')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.vendor')),
            ],
            options={
                'db_table': 'purchases_completion_certificate',
                'ordering': ['-document_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompletionCertificateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='completion_certificates/')),
                ('document_number', models.CharField(blank=True, max_length=255, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchase.completioncertificate')),
                ('master_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.grnsesdocument')),
            ],
            options={
                'db_table': 'purchases_completion_certificate_document',
                'unique_together': {('cc', 'master_document')},
            },
        ),
    ]
