# Generated by Django 5.0.6 on 2026-06-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_completioncertificate_completioncertificatedocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grnsesdocument',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='grnsesdocument',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='grnsesdocument',
            name='type',
        ),
        migrations.AddField(
            model_name='grnsesdocument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grnsesdocument',
            name='name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completioncertificate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grnsesdocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
