# Generated by Django 5.0.6 on 2026-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_alter_grnsesdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grnsesdocument',
            options={'ordering': ['document_name']},
        ),
        migrations.RemoveField(
            model_name='grnsesdocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='grnsesdocument',
            name='name',
        ),
        migrations.AddField(
            model_name='grnsesdocument',
            name='document_name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grnsesdocument',
            name='type',
            field=models.CharField(choices=[('GRN', 'GRN'), ('SES', 'SES')], default='GRN', max_length=10),
        ),
        migrations.AlterField(
            model_name='grnsesdocument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
