# Generated by Django 5.0.6 on 2026-06-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_alter_grnsesdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completioncertificate',
            name='approval_status',
            field=models.CharField(default='draft', max_length=50),
        ),
    ]
