# Generated by Django 5.0.6 on 2026-06-28 05:26

import apps.purchase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_alter_completioncertificate_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completioncertificatedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.purchase.models.cc_document_upload_path),
        ),
    ]
