# Generated by Django 5.0.6 on 2026-06-28 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_alter_completioncertificatedocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='completioncertificate',
            name='void_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_ccs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completioncertificate',
            name='void_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completioncertificate',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
