# Generated by Django 5.0.6 on 2026-06-28 14:34

import apps.purchase.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0019_completioncertificate_void_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(max_length=100, unique=True)),
                ('document_date', models.DateField()),
                ('acceptance_date', models.DateField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('GRN', 'GRN'), ('SES', 'SES')], default='GRN', max_length=10)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('term_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('approval_status', models.CharField(default='draft', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('void_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.completioncertificate')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.vendor')),
                ('void_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_grns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchases_good_receipt_note',
                'ordering': ['-document_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodReceiptNoteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.purchase.models.grn_document_upload_path)),
                ('document_number', models.CharField(blank=True, max_length=255, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchase.goodreceiptnote')),
                ('master_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.grnsesdocument')),
            ],
            options={
                'db_table': 'purchases_good_receipt_note_document',
                'unique_together': {('grn', 'master_document')},
            },
        ),
    ]
