# Generated by Django 5.0.6 on 2026-07-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_goodreceiptnote_goodreceiptnotedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='close_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='received_qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
