# Generated by Django 5.0.6 on 2026-07-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0021_purchaseorder_close_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
