# Generated by Django 4.2.30 on 2026-07-06 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_receiptreport_tracking_last_update_and_more'),
        ('purchase', '0022_purchaseorder_is_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('tax_date', models.DateField()),
                ('tax_number', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('half_paid', 'Half Paid'), ('full_paid', 'Full Paid'), ('void', 'Void')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_invoices', to=settings.AUTH_USER_MODEL)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='purchase.goodreceiptnote')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='purchase.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='purchase.vendor')),
            ],
            options={
                'verbose_name': 'Purchase Invoice',
                'db_table': 'purchases_invoice_header',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='purchase.purchaseinvoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_details', to='inventory.item')),
            ],
            options={
                'db_table': 'purchases_invoice_detail',
                'ordering': ['invoice', 'order_no', 'id'],
            },
        ),
    ]
