# Generated by Django 5.0.6 on 2026-07-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_receiptreport_tracking_last_update_and_more'),
        ('purchase', '0023_purchaseinvoice_purchaseinvoicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='receipt_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='inventory.receiptreport'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='purchase.goodreceiptnote'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoicePaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('term_number', models.PositiveIntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='purchase.purchaseinvoice')),
            ],
            options={
                'db_table': 'purchases_invoice_payment_term',
                'ordering': ['invoice', 'term_number', 'id'],
            },
        ),
    ]
