# Generated by Django 5.0.6 on 2026-07-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0024_purchaseinvoice_invoice_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='tax_number_pph',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='tax_number_ppn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
