# Generated by Django 5.0.6 on 2026-07-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0025_purchaseinvoice_tax_number_pph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('half_paid', 'Half Paid'), ('full_paid', 'Full Paid'), ('void', 'Void')], default='not_paid', max_length=20),
        ),
    ]
