# Generated by Django 4.2.30 on 2026-06-01 08:20

import apps.organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='signature_draw',
            field=models.TextField(blank=True, help_text='Base64 canvas drawing tanda tangan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Upload gambar tanda tangan', null=True, upload_to=apps.organization.models.signature_upload_path),
        ),
    ]
