# Generated by Django 5.0.6 on 2026-06-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='smtp_host',
            field=models.CharField(blank=True, default='sandbox.smtp.mailtrap.io', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_port',
            field=models.IntegerField(default=2525),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
