# Generated by Django 5.0.6 on 2026-06-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_company_smtp_host_company_smtp_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='smtp_from_email',
            field=models.CharField(blank=True, default='noreply@example.com', help_text='Alamat pengirim untuk email otomatis', max_length=255),
        ),
    ]
