# Generated by Django 4.2.30 on 2026-06-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('organization', '0002_employee_signature_draw_employee_signature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('tax_number', models.CharField(blank=True, default='', max_length=50)),
                ('nppkp', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField(blank=True, default='')),
                ('country', models.CharField(default='Indonesia', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('area_code', models.CharField(choices=[('other', '[Other] Other'), ('jakarta', 'Jakarta'), ('bandung', 'Bandung'), ('surabaya', 'Surabaya')], default='other', max_length=20)),
                ('phone_1', models.CharField(max_length=30)),
                ('phone_2', models.CharField(blank=True, default='', max_length=30)),
                ('fax', models.CharField(blank=True, default='', max_length=30)),
                ('currency', models.CharField(choices=[('IDR', 'IDR'), ('USD', 'USD'), ('EUR', 'EUR'), ('SGD', 'SGD')], default='IDR', max_length=5)),
                ('default_price_group', models.CharField(blank=True, default='', max_length=50)),
                ('tolerance_difference', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_kawasan_berikat', models.BooleanField(default=False)),
                ('is_sister_company', models.BooleanField(default=False)),
                ('item_type_asset', models.BooleanField(default=True)),
                ('item_type_fg', models.BooleanField(default=True)),
                ('item_type_rm', models.BooleanField(default=True)),
                ('item_type_supplies', models.BooleanField(default=True)),
                ('item_type_wip', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('hold', 'Hold')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Customer Categories',
                'db_table': 'sales_customer_category',
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sales_customer_group',
            },
        ),
        migrations.CreateModel(
            name='CustomerTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due', models.CharField(choices=[('tanpa_cicilan', 'Tanpa Cicilan'), ('net_30', 'Net 30'), ('net_60', 'Net 60'), ('cod', 'COD')], default='tanpa_cicilan', max_length=20)),
                ('balance_due_days', models.PositiveIntegerField(default=0)),
                ('tax_code', models.CharField(choices=[('ppn_11', 'PPN 11 %'), ('ppn_0', 'PPN 0 %'), ('non', 'Non PPN')], default='ppn_11', max_length=20)),
                ('use_customer_tax_code', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='sales.customer')),
            ],
            options={
                'db_table': 'sales_customer_terms',
            },
        ),
        migrations.CreateModel(
            name='CustomerContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('home_address', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('home_phone', models.CharField(blank=True, default='', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='sales.customer')),
            ],
            options={
                'db_table': 'sales_customer_contact_person',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.customercategory'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='organization.company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customergroup'),
        ),
        migrations.CreateModel(
            name='CustomerLinkedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('ar_invoice', 'A/R to be Invoiced'), ('ar', 'A/R'), ('deposit', 'Customer Deposit'), ('down_payment', 'Customer Down Payment')], max_length=30)),
                ('currency_scope', models.CharField(choices=[('all', 'All'), ('IDR', 'IDR'), ('USD', 'USD'), ('EUR', 'EUR'), ('SGD', 'SGD')], default='all', max_length=5)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='sales.customer')),
            ],
            options={
                'db_table': 'sales_customer_linked_account',
                'unique_together': {('customer', 'account_type', 'currency_scope')},
            },
        ),
    ]
